---
# DESCRIPTION: Github actions config
#
# This file ONLY is placed under the Creative Commons Public Domain, for
# any use, without warranty, 2020 by Wilson Snyder.
# SPDX-License-Identifier: CC0-1.0

name: build-test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  vlt:
    runs-on: ubuntu-24.04
    name: build and test
    env:
      CACHE_KEY: build-ubuntu-24.04-gcc-ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 4Gi
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Restore cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CACHE_KEY }}-${{ github.sha }}
          restore-keys: |
            ${{ env.CACHE_KEY }}

      - name: Install packages for build
        run: |
          cd submodules/verilator && bash ci/ci-install.bash build
          sudo cpan -fi Bit::Vector  # For t_cores_el2_cmark

      - name: Build
        run: |
          cd submodules/verilator
          bash ci/ci-build.bash --compiler gcc --prefix "${{ github.workspace }}/install" --ccwarn

      - name: Save cache  # So faster to rerun if a test below fails
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CACHE_KEY }}-${{ github.sha }}

      - name: Install packages for tests
        run: |
          ( cd submodules/verilator && bash ci/ci-install.bash test )
          pipx install --system-site-packages submodules/astsee

      - name: Test
        run: |
          export VERILATOR_ROOT=$GITHUB_WORKSPACE/submodules/verilator
          source /opt/pipx/venvs/astsee/bin/activate
          make test
